# Generated by Django 3.1.3 on 2020-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skill',
            field=models.ManyToManyField(to='skill.Skill', verbose_name='skill'),
        ),
    ]
